In [94]:
import numpy as np 
import pandas as pd
data = {"A" : [1 , 2 , 3 , 4 ] , "B" : [np.NaN , np.NaN , 4 , 8 ] }

In [95]:
df = pd.DataFrame(data)
#using simple imputer means that
from sklearn.impute import SimpleImputer 
si = SimpleImputer(missing_values = np.nan , strategy = 'mean' )
si.fit(df)
ne_df = si.transform(df)
n = pd.DataFrame(ne_df , columns = df.columns.values)

In [96]:
n

A    B
0  1.0  6.0
1  2.0  6.0
2  3.0  4.0
3  4.0  8.0

In [97]:
# or we use fill na method 
dfs = df.fillna(df.mean())

In [98]:
dfs

A    B
0  1  6.0
1  2  6.0
2  3  4.0
3  4  8.0

In [99]:
import pandas as pd
df = pd.DataFrame([
['green', 'M', 10.1, 'class2'],
['red', 'L', 13.5, 'class1'],
['blue', 'XL', 15.3, 'class2']])
df.columns = ['color', 'size', 'price', 'classlabel']
df
dfs = df.copy()

In [100]:
size_mapping = {'M' : 1 , 'L' : 2 , 'XL' : 3 }
df['size'] = df['size'].map(size_mapping)

In [101]:
df

color  size  price classlabel
0  green     1   10.1     class2
1    red     2   13.5     class1
2   blue     3   15.3     class2

In [102]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}
df['size'] = df['size'].map(inv_size_mapping)

In [103]:
df

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

In [104]:
for k , v in size_mapping.items():
    print( k , v)

M 1
L 2
XL 3


## Encooding Class Label

In [105]:
class_mapping = {label : i for i ,label  in enumerate(np.unique(df['classlabel']))}
class_mapping

{'class1': 0, 'class2': 1}

In [106]:
df['classlabel'] = df['classlabel'].map(class_mapping)
df

color size  price  classlabel
0  green    M   10.1           1
1    red    L   13.5           0
2   blue   XL   15.3           1

### Reverse Class Label 

In [107]:
class_mapping

{'class1': 0, 'class2': 1}

In [108]:
class_inv_mapping = {idx : label for label , idx in class_mapping.items()}
df['classlabel_inv'] = df['classlabel'].map(class_inv_mapping)

In [109]:
dfs

color size  price classlabel
0  green    M   10.1     class2
1    red    L   13.5     class1
2   blue   XL   15.3     class2

## Using scikitlearn label encooder class


In [110]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(dfs['classlabel'].values)
y

array([1, 0, 1])

In [111]:
#inversing the process 
le.inverse_transform(y)

array(['class2', 'class1', 'class2'], dtype=object)

##  OneHotEncoding using Pandas
 ##### for unorder data 

In [112]:
df = pd.read_csv("cars.csv")

In [113]:
ohe_df = pd.get_dummies(data = df , columns = ['fuel' , 'owner'])


In [114]:
ohe_df

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000         0            1         0   
1       Skoda     120000         370000         0            1         0   
2       Honda     140000         158000         0            0         0   
3     Hyundai     127000         225000         0            1         0   
4      Maruti     120000         130000         0            0         0   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000         0            0         0   
8124  Hyundai     119000         135000         0            1         0   
8125   Maruti     120000         382000         0            1         0   
8126     Tata      25000         290000         0            1         0   
8127     Tata      25000         290000         0            1         0   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0               0                  1                           0   
1               0                  0                           0   
2               1                  0                           0   
3               0                  1                           0   
4               1                  1                           0   
...           ...                ...                         ...   
8123            1                  1                           0   
8124            0                  0                           1   
8125            0                  1                           0   
8126            0                  1                           0   
8127            0                  1                           0   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                      0                     0                  0  
1                      1                     0                  0  
2                      0                     0                  1  
3                      0                     0                  0  
4                      0                     0                  0  
...                  ...                   ...                ...  
8123                   0                     0                  0  
8124                   0                     0                  0  
8125                   0                     0                  0  
8126                   0                     0                  0  
8127                   0                     0                  0  

[8128 rows x 12 columns]

##  $$  K - 1    One Hot Encooding
$$ 


In [115]:
#we are just dropping first columsn 
k1_ohe_df = pd.get_dummies(df ,  columns = ['fuel' , 'owner'] , drop_first = True)

In [116]:
k1_ohe_df.shape , ohe_df.shape , df.shape
#why 10 columsn cuz fuel ko first ra owner ko first columsn deleted xa 

((8128, 10), (8128, 12), (8128, 5))

In [117]:
#comparision 
k1_ohe_df

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000            1         0            0   
1       Skoda     120000         370000            1         0            0   
2       Honda     140000         158000            0         0            1   
3     Hyundai     127000         225000            1         0            0   
4      Maruti     120000         130000            0         0            1   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000            0         0            1   
8124  Hyundai     119000         135000            1         0            0   
8125   Maruti     120000         382000            1         0            0   
8126     Tata      25000         290000            1         0            0   
8127     Tata      25000         290000            1         0            0   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              0                   0                     0   
1                              0                   1                     0   
2                              0                   0                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
8123                           0                   0                     0   
8124                           1                   0                     0   
8125                           0                   0                     0   
8126                           0                   0                     0   
8127                           0                   0                     0   

      owner_Third Owner  
0                     0  
1                     0  
2                     1  
3                     0  
4                     0  
...                 ...  
8123                  0  
8124                  0  
8125                  0  
8126                  0  
8127                  0  

[8128 rows x 10 columns]

In [118]:
ohe_df

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000         0            1         0   
1       Skoda     120000         370000         0            1         0   
2       Honda     140000         158000         0            0         0   
3     Hyundai     127000         225000         0            1         0   
4      Maruti     120000         130000         0            0         0   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000         0            0         0   
8124  Hyundai     119000         135000         0            1         0   
8125   Maruti     120000         382000         0            1         0   
8126     Tata      25000         290000         0            1         0   
8127     Tata      25000         290000         0            1         0   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0               0                  1                           0   
1               0                  0                           0   
2               1                  0                           0   
3               0                  1                           0   
4               1                  1                           0   
...           ...                ...                         ...   
8123            1                  1                           0   
8124            0                  0                           1   
8125            0                  1                           0   
8126            0                  1                           0   
8127            0                  1                           0   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                      0                     0                  0  
1                      1                     0                  0  
2                      0                     0                  1  
3                      0                     0                  0  
4                      0                     0                  0  
...                  ...                   ...                ...  
8123                   0                     0                  0  
8124                   0                     0                  0  
8125                   0                     0                  0  
8126                   0                     0                  0  
8127                   0                     0                  0  

[8128 rows x 12 columns]

## using skitlearn class 


In [176]:

df = pd.read_csv("cars.csv")
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test  = train_test_split(df.iloc[:,0:4] , df.iloc[: , -1] , test_size = 0.2  , random_state = 2 )

In [177]:
x_train

brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner
...        ...        ...     ...           ...
3606      Ford      35000  Diesel   First Owner
5704    Maruti     120000  Petrol   First Owner
6637      Tata      15000  Petrol   First Owner
2575    Maruti      32500  Diesel  Second Owner
7336     Isuzu     121000  Diesel   First Owner

[6502 rows x 4 columns]

In [178]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop = 'first' , sparse = False , dtype = np.int32)

In [179]:
x_train_new = ohe.fit_transform(x_train[['fuel'  , 'owner']])

D:\software\python\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [180]:
x_test_new = ohe.transform(x_test[['fuel' , 'owner']])

In [187]:
np.hstack((x_test[['brand' , 'km_driven']].values, x_test_new))

array([['Hyundai', 80000, 0, ..., 0, 0, 0],
       ['Mahindra', 70000, 1, ..., 1, 0, 0],
       ['Toyota', 68089, 0, ..., 0, 0, 0],
       ...,
       ['Maruti', 40000, 0, ..., 0, 0, 0],
       ['Hyundai', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 50000, 1, ..., 0, 0, 0]], dtype=object)

## np.hstack

In [194]:
#hstack code 
x = np.arange( 2 , 10 )

In [195]:
y = np.arange( 10 , 20 )

In [196]:
x

array([2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [199]:
np.hstack((x,y))

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

## Mininmizing dimension ( one hot enccoding using only most frequent variables) 

suppose yout have **40 Cars Brand** Out of which **10 Car Brands** have very low **frequency** while others have very hight 
frequency 

#### THen we can reduce the dimension by puttling all low frequent cars on new others category ### 


In [203]:
df = pd.read_csv("cars.csv")

In [210]:
counts = df['brand'].value_counts()
counts

Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: brand, dtype: int64

In [211]:
threshold = 100  #min 100 frequency 
rep = counts[counts < threshold].index

In [213]:
rep # cars which has less than 100 frequency 

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object')

In [231]:
pd.get_dummies(df['brand'].replace(rep , "others") , drop_first = True)

Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  Tata  \
0             0     0      0        0         0       1        0      0     0   
1             0     0      0        0         0       0        0      1     0   
2             0     0      1        0         0       0        0      0     0   
3             0     0      0        1         0       0        0      0     0   
4             0     0      0        0         0       1        0      0     0   
...         ...   ...    ...      ...       ...     ...      ...    ...   ...   
8123          0     0      0        1         0       0        0      0     0   
8124          0     0      0        1         0       0        0      0     0   
8125          0     0      0        0         0       1        0      0     0   
8126          0     0      0        0         0       0        0      0     1   
8127          0     0      0        0         0       0        0      0     1   

      Toyota  Volkswagen  others  
0          0           0       0  
1          0           0       0  
2          0           0       0  
3          0           0       0  
4          0           0       0  
...      ...         ...     ...  
8123       0           0       0  
8124       0           0       0  
8125       0           0       0  
8126       0           0       0  
8127       0           0       0  

[8128 rows x 12 columns]