In [1]:
import pandas as pd 
import numpy as np 

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.sample(5)

PassengerId  Survived  Pclass                                Name  \
292          293         0       2              Levy, Mr. Rene Jacques   
662          663         0       1          Colley, Mr. Edward Pomeroy   
861          862         0       2         Giles, Mr. Frederick Edward   
537          538         1       1                 LeRoy, Miss. Bertha   
539          540         1       1  Frolicher, Miss. Hedwig Margaritha   

        Sex   Age  SibSp  Parch         Ticket      Fare Cabin Embarked  
292    male  36.0      0      0  SC/Paris 2163   12.8750     D        C  
662    male  47.0      0      0           5727   25.5875   E58        S  
861    male  21.0      1      0          28134   11.5000   NaN        S  
537  female  30.0      0      0       PC 17761  106.4250   NaN        C  
539  female  22.0      0      2          13568   49.5000   B39        C

In [4]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [5]:


#dropping unnecessary columsn 
df.drop(columns = ['Cabin' , 'Ticket' , 'Name' ,'PassengerId'] , inplace = True)

In [6]:
#
from sklearn.model_selection import train_test_split 
xtrain , xtest , ytrain , ytest  = train_test_split(df.iloc[: , 1:] , df.iloc[: , 0].values.reshape( -1  , 1 ) , test_size  = 0.2 , random_state = 2 )

In [7]:
xtrain.isnull().sum() # 2 null values in embarked 

Pclass        0
Sex           0
Age         148
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [8]:
xtest.isnull().sum() #29 null values in ['Age']

Pclass       0
Sex          0
Age         29
SibSp        0
Parch        0
Fare         0
Embarked     0
dtype: int64

In [9]:
from sklearn.impute import SimpleImputer 
si = SimpleImputer(strategy = 'most_frequent') 
xtrain_age = si.fit_transform(xtrain[['Age']])
xtest_age  = si.fit_transform(xtest[['Age']])

# also for embarked columns 
xtrain_Embarked = si.fit_transform(xtrain[['Embarked']])
xtest_Embarked  = si.fit_transform(xtest[['Embarked']])

In [10]:
print("xtrain-age total null no :   " , (xtrain_age == np.NaN).sum()) 
print("xtest-age total null no  :   " , (xtest_age == np.NaN).sum()) 

xtrain-age total null no :    0
xtest-age total null no  :    0


In [11]:
print("xtrain-Embarked total null no :   " , (xtrain_Embarked == np.NaN).sum()) 
print("xtest-Embarked total  null no :   " , (xtrain_Embarked == np.NaN).sum()) 

xtrain-Embarked total null no :    0
xtest-Embarked total  null no :    0


### One Hot Encooding Sex and Embarked 


In [12]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
ohe_sex = OneHotEncoder( sparse = False ,handle_unknown='ignore')
#xtrain_sex
xtrain_sex = ohe_sex.fit_transform(xtrain[['Sex']])
xtest_sex = ohe_sex.fit_transform(xtest[['Sex']])

#for embaked 
ohe_Embarked = OneHotEncoder( sparse = False ,handle_unknown='ignore')

xtrain_Embarked = ohe_Embarked.fit_transform(xtrain_Embarked)
xtest_Embarked  = ohe_Embarked.fit_transform(xtest_Embarked)

D:\software\python\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
D:\software\python\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
D:\software\python\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
D:\software\python\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignor

In [14]:
xtrain_Embarked

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [15]:
df['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [16]:
df.head(2)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C

In [17]:
#Extracing others columns  
xtrain_rem = xtrain.iloc[: , [0 , 3 , 4  ,  5  ]]

In [18]:
#also for xtest
xtest_rem = xtest.iloc[: , [ 0 , 3 , 4  , 5]]

In [19]:
xtrain_rem

Pclass  SibSp  Parch      Fare
30        1      0      0   27.7208
10        3      1      1   16.7000
873       3      0      0    9.0000
182       3      4      2   31.3875
876       3      0      0    9.8458
..      ...    ...    ...       ...
534       3      0      0    8.6625
584       3      0      0    8.7125
493       1      0      0   49.5042
527       1      0      0  221.7792
168       1      0      0   25.9250

[712 rows x 4 columns]

#### CONCATINATING

In [20]:
xtrain_transform = np.concatenate((xtrain_rem.values , xtrain_age  , xtrain_Embarked , xtrain_sex) , axis = 1 )

In [21]:
xtest_transform = np.concatenate((xtest_rem.values , xtest_age  , xtest_Embarked , xtest_sex) , axis = 1 )

In [22]:
xtrain_transform

array([[1., 0., 0., ..., 0., 0., 1.],
       [3., 1., 1., ..., 1., 1., 0.],
       [3., 0., 0., ..., 1., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 1., 0., 1.]])

In [23]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(xtrain_transform , ytrain)

DecisionTreeClassifier()

In [24]:
ypred = clf.predict(xtest_transform)

In [25]:
ytest.shape

(179, 1)

In [26]:
((clf.predict(xtest_transform) - ytest.reshape(-1))**2 ).sum()

43

In [27]:
clf.predict(xtest_transform) - ytest.reshape(-1)

array([-1,  0,  0,  1,  0,  0, -1,  0, -1,  0,  0,  0,  0, -1, -1, -1,  0,
        0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  1,
       -1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0, -1, -1,  1,
        0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
        0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  1, -1,  0, -1,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0, -1,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, -1,  0,  0,  1,
        0,  1, -1,  0,  0,  0,  1,  0,  1,  0,  0,  0,  1, -1,  0,  1,  0,
        0,  0,  0,  0,  0,  0, -1, -1,  0,  1, -1,  0,  0,  0, -1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  1], dtype=int64)

In [28]:
#so convert -14 into 1  one and mesure error 
(clf.predict(xtest_transform) - ytest.reshape(-1))**2

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1], dtype=int64)

In [29]:
a =[True , False ] 
x = pd.DataFrame(a)

In [30]:
#on total  179 data 44 were incorrect 
ytest.reshape(-1).shape


(179,)

In [31]:
#cal percentage 
(44 / 179 )*100

24.581005586592177

In [32]:
#23.58 percentage error 


In [33]:
#check accuracy 
from sklearn.metrics import accuracy_score
accuracy_score(ytest , ypred)

0.7597765363128491

In [34]:
0.7541*100


75.41

In [35]:
75.41-100


-24.590000000000003

## Importing pickel 

In [36]:
import pickle

In [42]:
pickle.dump(ohe_sex, open('ohe_sex.pkl' , 'wb'))
pickle.dump(ohe_Embarked  , open('ohe_embarked.pkl' , 'wb'))
pickle.dump(clf, open('clf.pkl' , 'wb'))