In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

## Importing  data sets

In [2]:
from sklearn.datasets import load_diabetes 
x , y = load_diabetes(return_X_y=True)

In [3]:
x.shape  , y.shape

((442, 10), (442,))

### Train Test Split 

In [4]:
xtrain , xtest , ytrain ,ytest  = train_test_split(x , y ,test_size =  0.2 , random_state = 2 ) 

## from sklearn class 

In [5]:
lr = LinearRegression() 
lr.fit(xtrain , ytrain) 
"b ko val " , lr.intercept_ , " " , "slope ko values haru " ,  lr.coef_

('b ko val ',
 151.88331005254167,
 ' ',
 'slope ko values haru ',
 array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]))

In [6]:
lr.predict(xtest) 

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

#### notice : That Mine prvious own gdregressor class cannot halden multidimentional features so lets make another class  which can handel multidimentional features and predict


In [7]:
class GDRegressor : 
    def __init__ (self , learning_rate = 0.01 , epochs = 98  ):
        self.learning_r = learning_rate 
        self.epochs = epochs 
        self.m = None 
        self.b = None 
        
    def fit(self , xtrain ,ytrain) :  
        # basically prediction nikalna keke  cahinxa tai value of val tapaune ho yeha
        # for eg  y = mx + b so m , ra b ko value tapaune yeta ani predict garne 
        # m ra b ko minima dine value hai 
        
        # set  first coeff = 0 
        self.b = 0 
        self.m = np.ones(xtrain.shape[1])
        
        #pahela jastai b = b - self.lr * slope_m  yestai parale 
        #update all intercept and coeff 
          
            #we know b = b - lr*slope_b  for 1 'd' for multi 
            #and slope_of _ b here is a derivation of loss function with respect to b so same likke then 
       
    
    # self.b = self.b - b_ko_slope we dont know value for bko derivation so 
    #b_ko_slope = lossfunction ko derivation with respect to b 
    #b ko slope =  -2 * np.mean(ytrain - yhat) 

    #fer yhat?? 
    
    #yhat   = mx  + c 
              # xtrain , ra m matrix ma xa so dot product  
        
#okey start /////////////////////////////////////////////////////////////////////////

        for i in range(self.epochs):
            yhat = np.dot(xtrain , self.m ) + self.b 
            b_ko_slope = -2*np.mean(ytrain - yhat )
            self.b = self.b  - (self.learning_r * b_ko_slope ) 
              ## b ko value update bayo aabo m ko value update garnu paro
        
            m_ko_slope = -2 * np.dot((ytrain - yhat )  , xtrain ) /( xtrain.shape[0])
            self.m  = self.m - (self.learning_r * m_ko_slope ) 
    
            
    
        
        
    def predict(self , xtest ) : #tai mx+ b but multidimentional bako bara 
        return np.dot(xtest , self.m ) + self.b 
        

In [8]:
np.ones(xtrain.shape[1])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
rg = GDRegressor(0.1, 100000)
rg.fit(xtrain , ytrain)

In [13]:
ypred1 = rg.predict(xtest)

In [14]:
r2_score(ytest , ypred1) 

0.44250952691934

In [ ]:
#fine thanks 
# - i will be adding figures after mine exam !!!!!!